services:
  sabnzbd-movies:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd-movies
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
    volumes:
      - /var/config/sabnzbd-movies:/config
      - /mnt/nas1/mattyflix:/mattyflix
    networks:
      - proxy
    ports:
      - 8080:8080
    restart: unless-stopped

  sabnzbd-series:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd-series
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
    volumes:
      - /var/config/sabnzbd-series:/config
      - /mnt/nas2/mattyflix:/mattyflix
    networks:
      - proxy
    ports:
      - 8081:8080
    restart: unless-stopped

  sabnzbd-music:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd-music
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
    volumes:
      - /var/config/sabnzbd-music:/config
      - /mnt/nas3/mattyflix:/mattyflix
    networks:
      - proxy
    ports:
      - 8082:8080
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
    volumes:
      - /var/config/sonarr:/config
      - /mnt/nas2/mattyflix:/mattyflix
    networks:
      - proxy
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
    volumes:
      - /var/config/radarr:/config
      - /mnt/nas1/mattyflix:/mattyflix
    networks:
      - proxy
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
    volumes:
      - /var/config/lidarr:/config
      - /mnt/nas3/mattyflix:/mattyflix
    ports:
      - 8686:8686
    networks:
      - proxy
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /var/config/jackett:/config
    networks:
      - proxy
    ports:
      - 9117:9117
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Detroit
    ports:
      - 5055:5055
    volumes:
      - /var/config/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.middlewares.seerr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.seerr-secure.entrypoints=https"
      - "traefik.http.routers.seerr-secure.rule=Host(`search.mattyflix.com`)"
      - "traefik.http.routers.seerr-secure.service=overseerr"
      - "traefik.http.routers.seerr-secure.tls=true"
      - "traefik.http.routers.seerr-secure.tls.certresolver=http"
      - "traefik.http.routers.seerr.entrypoints=http"
      - "traefik.http.routers.seerr.middlewares=seerr-https-redirect"
      - "traefik.http.routers.seerr.rule=Host(`search.mattyflix.com`)"
      - "traefik.http.services.seerr.loadbalancer.server.port=5055"
  
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /var/config/Tautulli/config:/config
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
    networks:
      - proxy
    ports:
      - 8181:8181
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.middlewares.tautulli-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.tautulli-secure.entrypoints=https"
      - "traefik.http.routers.tautulli-secure.rule=Host(`tautulli.mattyflix.com`)"
      - "traefik.http.routers.tautulli-secure.service=tautulli"
      - "traefik.http.routers.tautulli-secure.tls=true"
      - "traefik.http.routers.tautulli-secure.tls.certresolver=http"
      - "traefik.http.routers.tautulli.entrypoints=http"
      - "traefik.http.routers.tautulli.middlewares=tautulli-https-redirect"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.mattyflix.com`)"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
    volumes:
      - /var/config/prowlarr:/config
    networks:
      - proxy
    ports:
      - 9696:9696
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
    volumes:
      - /var/config/bazarr/config:/config
      - /mnt/nas1/mattyflix/media/movies:/movies #optional
      - /mnt/nas2/mattyflix/media/series:/tv #optional
    networks:
      - proxy
    ports:
      - 6767:6767
    restart: unless-stopped
  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    environment:
      - PUID=1000
      - PGID=999
      - TZ=America/Detroit
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIMES=03:00 #optional
      - KOMETA_RUN=False #optional
      - KOMETA_TESTS=False #optional
      - KOMETA_NO_MISSING=False #optional
    networks:
      - proxy
    volumes:
      - /var/config/kometa/config:/config
    restart: unless-stopped

networks:
  proxy:
    external: true
